[main]
environ = "local"
project_root = "blogs"

[database]
drv_name = "mysql"
conn_urls = {
  local_mainDb = {
    conn_max_idle_time = 3000,
    max_open_conns = 10,
    url = "rommms:07261999@unix(/var/run/mysqld/mysqld.sock)/"
  },
  local_commentsDb = {
    conn_max_idle_time = 3000,
    max_open_conns = 10,
    url = "rommms:07261999@unix(/var/run/mysqld/mysqld.sock)/rommms.blogs-comments"
  },
  local_usersDb = {
    conn_max_idle_time = 3000,
    max_open_conns = 10,
    url = "rommms:07261999@unix(/var/run/mysqld/mysqld.sock)/rommms.blogs-users"
  },
  local_postsDb = {
    conn_max_idle_time = 3000,
    max_open_conns = 10, 
    url = "rommms:07261999@unix(/var/run/mysqld/mysqld.sock)/rommms.blogs-posts"
  },
  local_reactsDb = {
    conn_max_idle_time = 3000,
    max_open_conns = 10,
    url = "rommms:07261999@unix(/var/run/mysqld/mysqld.sock)/rommms.blogs-reacts"
  }
}
